### ISSUE TITLE
URGENT SHOPIFY INTEGRATION ISSUE

### ISSUE THREAD

**Issue by hommyshop** [wirecard/shopify-ee#3]
Hello,

I have installed the shopify-ee plugin. I entered the credentials as provided by WireCard. The plugin connects and appears in the checkout. However when trying to complete payment we get 'unauthorized' error.
<img width="1207" alt="Screenshot at Apr 09 13-27-54" src="https://user-images.githubusercontent.com/49198848/56014786-5987d200-5cff-11e9-838c-eb95d325f810.png">

In that case, I guess the credentials are incorrect.

but as a developer myself I took a closer look at this problem.

I have followed the shopify-ee instuctions exactly as written. It is very simple and it is not possible to do something wrong in there.

I even tried test credentials and they give the same error.
Username: test-credentials
Password: test-credentials

Then I made a completely clean new shopify store, and followed the instructions and got the same error.

The shopify-ee integration is broken.

Please fix this issue as soon as possible because we want to start processing sales through WireCard.

**Comment by jakubpolomsky** [comment]
Hello, the error messages are being reworked so that they are more clear. The issue here are wrong credentials. As the documentation states you can't just enter the credentials you have received during the onboarding. For the shopify app you need to get an username and password from the support team and they will configure your payment methods. As of now, your user was created and the credentials will be sent to you (it even maybe got sent to you already).

Kind regards and thank you for reporting

**Comment by hommyshop** [comment]
"As of now, your user was created and the credentials will be sent to you (it even maybe got sent to you already)." it was created and sent to us like a week ago but the entire week we are not able to get proper resolution apart from "please use our guide to integrate it".
